language: c
sudo: required
before_script:
- sudo add-apt-repository ppa:openscad/releases -y
- sudo apt-get update -q
- sudo apt-get install openscad
script: "./scripts/export-stl.sh"
install: true
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip-cleanup: true
  api_key:
    secure: XXX
  file:
  - battery_dummy-aa-pm.stl
  - battery_dummy-aa-p.stl
  - battery_dummy-aa-m.stl
  - battery_dummy-aaa-pm.stl
  - battery_dummy-aaa-p.stl
  - battery_dummy-aaa-m.stl
  on:
    repo: pfichtner/openscad-batterydummy
deploy.api-key:
- openssl aes-256-cbc -K $encrypted_15d61d6b57bb_key -iv $encrypted_15d61d6b57bb_iv
  -in github_deploy_key.enc -out github_deploy_key -d
