language: c
sudo: required
before_script:
- sudo add-apt-repository ppa:openscad/releases -y
- sudo apt-get update -q
- sudo apt-get install openscad
script: "./scripts/export-stl.sh"
install: true
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip-cleanup: true
  api_key:
    secure: Y5DESClfI/MgJ7hOvUjpDnidNCbMggBQx8NAKigBqIZDB0wb6d9Yxu8hhEFaipPpgyq46LqT/8/5Fxiwh5OizQyyEx9yOtsMxm+vZVUXlR0a9S7mSar/F6ER4GFHxzY1tQTM3HvWWAN8x2kHOqcw69NlJoSw/qujAW6wubVvzr4E1WRfE4ixY0vsx0Cus9QgpaINiKnb+iqELONcIMmUTkqhzFLAWACnmGHb99kRNY5o0EOEE/FEalEN/2NmZy4n9g1222Dt2ENZrkbJ8OL9HlL+6qF8uXTsfQzTIGjucVFoPttmoddygm5aaMooQ6a6+8tpZZQCLXd0z2VlttRvjsoDaD4zoalIlUq1kgwXBMb/ZKL2ol2fVHOLevhiROVJdVB2QHs0706/GdtOr1ywahwCDk9LEgJVy6Mf08ZooI6VWjL/7/TjnZTgOPA7JIXDMuq2OYwc1Mrn1RmUBnw/jLfnXK0vTJayrIoL55Fd5RmPHjk0Q8p87SXeDlOE0OcbS3iNmK34xCvkbEPsEoy5W9t7aNEDbaVa0uCnDzgw2XLHLBiVlGg2IswRelIbha4o6LBSdRAmG5th50thevgug3jHEMspyK7LBmNBsuzzNmPJM83IdkXx/OzeqQhUsu+nlWL9M4zVQ1HGELcLdslAi8ZoPvIiPV26Kyh9TFHWEn8=
  file:
  - battery_dummy-aa-pm.stl
  - battery_dummy-aa-p.stl
  - battery_dummy-aa-m.stl
  - battery_dummy-aaa-pm.stl
  - battery_dummy-aaa-p.stl
  - battery_dummy-aaa-m.stl
  on:
    repo: pfichtner/openscad-batterydummy
  api-key:
    secure: rhg13T0ltPPm8XayRBCSOfNbJqIhVEhB8BxpoAWLCJivZltFuso/iCuBBeL+Cdn/Zb34Xe+lzSpH8WokzPZIyZLM48aLi08Rsg1wVnMzZhh963+lJtOaaCuASJNHKeCs0vguKrlp9vNiaFZmYZL79tgh3y4Qv2GTOMRXAoKwPNMogjASQYZlefY1DWwlX94Ss2a5bBIR7dE+xVJQr2C/Y6P7dpa+pQ7kpKKapdehuG/9+jiuy5XKHGYHIIs78bfvp9MC2k9VOkygU5VPKFMJrCx3SPBr7VI8WA+Xp+r5b4Q5JEVtBxoU5Gy32zIDNIhPt7gtGqIC/mZxl2pCoLVyYT6P6ARVkNe0ENV9AMI93duEzfY4XIMKUDE4W8Qtr3rNKR+yTG7vOQRzpPwiTHMzfeAcyHfJwDxQRJg1yBE3Zet4dP76LrIoNr4MzyZn9zfcP066W7HrxHo9MXRzrT6NuYnD5e97sRpvfiuO3VFbutntot0ZXPgx/i5BYamrakny8BhhYhsI0uPrw1v0BCTjZu/W1VskzVW9Kt/Rc4foMuSo5RN/nXwXPBWY1ZPagC43NErvPKNTegG8GRWe/k+FRM6zM4abw+MC/Cpti677kez56I5NVopaD4UZzgvKisBml5ZS4MTGMs+hAfpnCwsfRVJ0iklaDTyAWDZJmvmoA3s=
deploy.api-key:
- openssl aes-256-cbc -K $encrypted_15d61d6b57bb_key -iv $encrypted_15d61d6b57bb_iv
  -in github_deploy_key.enc -out github_deploy_key -d
