language: c
sudo: required
addons:
  apt:
    sources:
    - sourceline: 'ppa:openscad/releases'
    packages:
    - openscad
script: "./scripts/export-stl.sh"
install: true
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: A7T0lIK1XXwZa8T4oJwq6N6hqNSJIQZ3xLWVIP2K91tUYLavcb1G8Ni+dDJpqF/BVQBb5BuiPV99ecTdohMsLxwIYv52HnkxCOg818nj2mdRyA0wYsN/rtcDSGaYXvMI+2oAJW0OABKm2sP0j2DfyFYrLCdCwJlVkyF9TK3wJVtLD+4BAqwQ8D0n/xRzZHY2T1XWeoqXJYR+skVr0Fwpj/r8OT+RF6AgGii8108kk1gHFgQo5iiW0aqseUNq1EoMYgAy1eYI9M2Rk+qrKH5qOUNtaqUS0iyvkwpvOEPCoS7MRe2Nd4WLTtT6fViMmzPPIFdvFqgaZiVZj/FtGp7xozV7RiPUWZIkXvsBGYITFHqrv0MQwHdQd+NKhk0cLj5kihqRIyuW2Gjuz7/7yzT6waKXin9XqWS8/V0oaCjX9hKvKq0SVRH8F/cUy7+EA6qWIm0yHG7hrYC8gg4Te+cinWefXXsPR0RUEeYD5CdMYMHbaMs3rXMsaOmC4U2ONEhzVHb5AiPlV3j9rYFqyXgpsSXESX1ZuDWkNXDu1pyd9XCproiAjPY3CCSOtpYQOylvZrQj78/M/so/1i54xpG8EZX4PnsjXNYarKfNTOeiZdXh1SSVLKuMaNSZJZTbJoKCv1Wft3J5PrPApr1TWmq+onF8CncJ0rX82tSfmfD000M=
  file: 
    - battery_dummy-aa-pm.stl
    - battery_dummy-aa-p.stl
    - battery_dummy-aa-m.stl
    - battery_dummy-aaa-pm.stl
    - battery_dummy-aaa-p.stl
    - battery_dummy-aaa-m.stl
  on:
    repo: pfichtner/openscad-batterydummy
