sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install openscad

script: 
- openscad -D '$plustterminal_drilling=true'  -D '$minusterminal_drilling=false' -o battery_dummy-1.stl battery_dummy.scad 
- openscad -D '$plustterminal_drilling=false' -D '$minusterminal_drilling=true'  -o battery_dummy-2.stl battery_dummy.scad 

install: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: token-env-name
  keep-history: true
  on:
    branch: master


