language: c
sudo: required
before_script:
- sudo add-apt-repository ppa:openscad/releases -y
- sudo apt-get update -q
- sudo apt-get install openscad
script: "./scripts/export-stl.sh"
install: true
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip-cleanup: true
  api_key:
    secure: Y5DESClfI/MgJ7hOvUjpDnidNCbMggBQx8NAKigBqIZDB0wb6d9Yxu8hhEFaipPpgyq46LqT/8/5Fxiwh5OizQyyEx9yOtsMxm+vZVUXlR0a9S7mSar/F6ER4GFHxzY1tQTM3HvWWAN8x2kHOqcw69NlJoSw/qujAW6wubVvzr4E1WRfE4ixY0vsx0Cus9QgpaINiKnb+iqELONcIMmUTkqhzFLAWACnmGHb99kRNY5o0EOEE/FEalEN/2NmZy4n9g1222Dt2ENZrkbJ8OL9HlL+6qF8uXTsfQzTIGjucVFoPttmoddygm5aaMooQ6a6+8tpZZQCLXd0z2VlttRvjsoDaD4zoalIlUq1kgwXBMb/ZKL2ol2fVHOLevhiROVJdVB2QHs0706/GdtOr1ywahwCDk9LEgJVy6Mf08ZooI6VWjL/7/TjnZTgOPA7JIXDMuq2OYwc1Mrn1RmUBnw/jLfnXK0vTJayrIoL55Fd5RmPHjk0Q8p87SXeDlOE0OcbS3iNmK34xCvkbEPsEoy5W9t7aNEDbaVa0uCnDzgw2XLHLBiVlGg2IswRelIbha4o6LBSdRAmG5th50thevgug3jHEMspyK7LBmNBsuzzNmPJM83IdkXx/OzeqQhUsu+nlWL9M4zVQ1HGELcLdslAi8ZoPvIiPV26Kyh9TFHWEn8=
  file:
  - battery_dummy-aa-pm.stl
  - battery_dummy-aa-p.stl
  - battery_dummy-aa-m.stl
  - battery_dummy-aaa-pm.stl
  - battery_dummy-aaa-p.stl
  - battery_dummy-aaa-m.stl
  on:
    repo: pfichtner/openscad-batterydummy
  api-key:
    secure: etfe4cZHPognze+ZIL22CV3Qbugqe1YzKZagBVdrFxZH1/YLGNGNvvtjrB+zJI/T/4npK+BEsta5kaCPvSo7FSHclCL7Thbkj0EzsFPR6VWQm9Sgd6lIcsj2aBTEt509Z1BOYuTr6AZI8NbqsMca/w/7Ng+fIelJmlL8pC6viy+9DdL7QhpIMP3akNU0HErMb+KaW4GvoVpoMm85CVHVc2sLEo5v9dFdEVUiGTmaT36HcrcBtdzR1BMHdi9uLx/HZTp6LQIwAjgv4V/wWcIpUzPHU8qZ3L/PCWaKzAkJRbrF26f21wn8iQKaEHNmlFukhHdfl5Kzds4VkOWHZ7CZRVpA8Hb9tPyl89kG7mwSO+lOBl8ENnBXSNG8cDiEDE/vkXnhDDMaJEzfW0B/CUJ1mGYeFZu60y+eLqYzh5rNjIuzpK23PBrEuKlAU8LHVxPHJROdm8kIy6ustDlK4JsYbxryxTQ07nI7lpLGOzgXGTL5MMXV9YpCU6yoilgw4eDQKZpVyd0I+0GVPH03JPmctAHD3A04eUwPZnwcrolBepxHanbeBQGD1CoO+KATyfjinNZaLpi3Lu/ghlOSSFw0E2fkUs/OWGBQJ5nIqFtpjkmq1was612T4e6QG4Hdug9VrDCiFSIyZTVunS3krLlRCgd+Rp8pxQ7ZJZh/PmZTjnQ=
