name: Build and Release

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up OpenSCAD
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad

    - name: Run Build Script
      run: ./scripts/export-stl.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: target
        path: "target/*"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: "target/*"
        makeLatest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
